
#pragma once
#include <map>
#include <string>

using namespace std;

namespace pandemic{
    //enum of all cities
    enum City{
        Algiers,
        Madrid,
        Paris,
        Atlanta,
        Chicago,
        Miami,
        Washington,
        Chennai,
        Beijing,
        Seoul,
        MexicoCity,
        Lima,
        SaoPaulo,
        BuenosAires,
        Bogota,
        Cairo,
        Istanbul,
        Baghdad,
        Riyadh,
        Bangkok,
        SanFrancisco,
        LosAngeles,
        Montreal,
        Delhi,
        Tehran,
        Karachi,
        Mumbai,
        Kolkata,
        London,
        Milan,
        StPetersburg,
        HoChiMinhCity,
        Jakarta,
        HongKong,
        Manila,
        Shanghai,
        Taipei,
        Moscow,
        Sydney,
        Johannesburg,
        Kinshasa,
        Lagos,
        Khartoum,
        Santiago,
        NewYork,
        Essen,
        Osaka,
        Tokyo
    };
    //map that include enum as a key and string of enum as a value
    inline map<City, string> stringOfCities{
        {Algiers, "Algiers"},
        {Atlanta, "Atlanta"},
        {Baghdad, "Baghdad"},
        {Bangkok, "Bangkok"},
        {Beijing, "Beijing"},
        {Bogota, "Bogota"},
        {BuenosAires, "BuenosAires"},
        {Cairo, "Cairo"},
        {Chennai, "Chennai"},
        {Chicago, "Chicago"},
        {Delhi, "Delhi"},
        {Essen, "Essen"},
        {HoChiMinhCity, "HoChiMinhCity"},
        {HongKong, "HongKong"},
        {Istanbul, "Istanbul"},
        {Jakarta, "Jakarta"},
        {Johannesburg, "Johannesburg"},
        {Karachi, "Karachi"},
        {Khartoum, "Khartoum"},
        {Kinshasa, "Kinshasa"},
        {Kolkata, "Kolkata"},
        {Lagos, "Lagos"},
        {Lima, "Lima"},
        {London, "London"},
        {LosAngeles, "LosAngeles"},
        {Madrid, "Madrid"},
        {Manila, "Manila"},
        {MexicoCity, "MexicoCity"},
        {Miami, "Miami"},
        {Milan, "Milan"},
        {Montreal, "Montreal"},
        {Moscow, "Moscow"},
        {Mumbai, "Mumbai"},
        {NewYork,"NewYork"},
        {Osaka, "Osaka"},
        {Paris, "Paris"},
        {Riyadh, "Riyadh"},
        {SanFrancisco, "SanFrancisco"},
        {Santiago, "Santiago"},
        {SaoPaulo, "SaoPaulo"},
        {Seoul, "Seoul"},
        {Shanghai, "Shanghai"},
        {StPetersburg, "StPetersburg"},
        {Sydney, "Sydney"},
        {Taipei, "Taipei"},
        {Tehran, "Tehran"},
        {Tokyo, "Tokyo"},
        {Washington, "Washington"}
    };

    inline map<string, City> stringNum{ 
        {"Algiers",Algiers},
        {"Atlanta", Atlanta},
        {"Baghdad", Baghdad}, {"Bangkok", Bangkok},
        {"Beijing", Beijing}, {"Beijing", Beijing},
        {"Bogota", Bogota}, {"BuenosAires", BuenosAires},
        {"Cairo", Cairo}, {"Chennai", Chennai},
        {"Chicago", Chicago}, {"Delhi", Delhi},
        {"Essen", Essen}, {"HoChiMinhCity", HoChiMinhCity},
        {"HongKong", HongKong}, {"Istanbul", Istanbul},
        {"Jakarta", Jakarta}, {"Johannesburg", Johannesburg},
        {"Karachi", Karachi}, {"Khartoum", Khartoum},
        {"Kinshasa", Kinshasa}, {"Kolkata", Kolkata},
        {"Lagos", Lagos}, {"Lima", Lima}, {"London", London},
        {"LosAngeles", LosAngeles}, {"Madrid", Madrid},
        {"Manila", Manila}, {"MexicoCity", MexicoCity},
        {"Miami", Miami}, {"Milan", Milan}, {"Montreal", Montreal},
        {"Moscow", Moscow}, {"Mumbai", Mumbai}, {"NewYork", NewYork},
        {"Osaka", Osaka}, {"Paris", Paris}, {"Riyadh", Riyadh},
        {"SanFrancisco", SanFrancisco}, {"Santiago", Santiago},
        {"SaoPaulo", SaoPaulo}, {"Seoul", Seoul}, {"Shanghai", Shanghai},
        {"StPetersburg", StPetersburg}, {"Sydney", Sydney}, {"Taipei", Taipei},
        {"Tehran", Tehran}, {"Tokyo", Tokyo}, {"Washington", Washington}
    };
}
